services:
  tor-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050"
    networks:
      - tor-network
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/log/tor/log | grep -q 'Bootstrapped 100% (done): Done' || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "23032:23032"
    depends_on:
      tor-proxy:
        condition: service_healthy
    networks:
      - tor-network

networks:
  tor-network:
    driver: bridge
